CATALOG = [
    {
        "id": "username",
        "title": "Никнейм (username)",
        "desc": "Справка: поиск публичных аккаунтов по нику. Не собирает ФИО и возраст.",
        "tools": [
            {
                "id": "handlehawk",
                "name": "HandleHawk",
                "repo": "https://github.com/C3n7ral051nt4g3ncy/HandleHawk",
                "purpose": "Проверка username сразу на нескольких платформах.",
                "input": "username",
            },
            {
                "id": "webcheck",
                "name": "WebCheck-OSINT",
                "repo": "https://github.com/mwakidenis/WebCheck-OSINT",
                "purpose": "Сводка по сайту/цели: заголовки, DNS, базовая разведка домена.",
                "input": "domain",
            },
        ],
    },
    {
        "id": "email_phone",
        "title": "Почта и телефон (только справка)",
        "desc": "Карточки утилит. Живой запуск по чужим email/телефону сюда не встроен.",
        "tools": [
            {
                "id": "yesitsme",
                "name": "yesitsme",
                "repo": "https://github.com/0x0be/yesitsme",
                "purpose": "Поиск Instagram-профиля по имени + фрагменту email/телефона. Нужна чужая/своя Instagram-сессия — в панель не интегрирую.",
                "input": "name + email/phone",
                "blocked": True,
            },
            {
                "id": "owltrack",
                "name": "OwlTrack",
                "repo": "https://github.com/IccTeam/OwlTrack",
                "purpose": "Трекинг/поиск по идентификаторам. Карточка только как справочник.",
                "input": "phone/email",
                "blocked": True,
            },
            {
                "id": "eyes",
                "name": "Eyes",
                "repo": "https://github.com/N0rz3/Eyes",
                "purpose": "Email/phone OSINT-фреймворк. Без живого запуска против людей.",
                "input": "email/phone",
                "blocked": True,
            },
            {
                "id": "traxosint",
                "name": "TraxOsint",
                "repo": "https://github.com/N0rz3/TraxOsint",
                "purpose": "OSINT по номеру. Каталог, не раннер.",
                "input": "phone",
                "blocked": True,
            },
        ],
    },
    {
        "id": "person",
        "title": "Профиль человека — не запускается",
        "desc": "Эти репозитории заточены под сборку личности. В панели только описание и ссылка.",
        "tools": [
            {
                "id": "daprofiler",
                "name": "DaProfiler",
                "repo": "https://github.com/daprofiler/DaProfiler",
                "purpose": "Сбор соцсетей, адресов, почт, телефонов, работы по имени/фамилии.",
                "input": "name + lastname",
                "blocked": True,
            },
            {
                "id": "ominis",
                "name": "Ominis-OSINT",
                "repo": "https://github.com/AnonCatalyst/Ominis-OSINT",
                "purpose": "Агрегатор разведки. Без запуска из этой панели.",
                "input": "query",
                "blocked": True,
            },
            {
                "id": "quidam",
                "name": "Quidam",
                "repo": "https://github.com/megadose/Quidam",
                "purpose": "Поиск людей по публичным следам.",
                "input": "person",
                "blocked": True,
            },
        ],
    },
    {
        "id": "social",
        "title": "Соцсети и мессенджеры (публичные страницы)",
        "desc": "Карточки. Нет скрейпа аккаунтов, нет поиска «где сидит этот человек».",
        "tools": [
            {
                "id": "telegramdb",
                "name": "TelegramDB",
                "repo": "https://github.com/TelegramDB/TelegramDB",
                "purpose": "Индекс публичных Telegram-групп/каналов. Поиск человека по группам сюда не подключаю.",
                "input": "keyword / public entity",
                "blocked": True,
            },
            {
                "id": "facebook_totem",
                "name": "facebook_totem",
                "repo": "https://github.com/megadose/facebook_totem",
                "purpose": "Публичная реклама Facebook Page (охват, бюджет объявлений), не профиль физлица.",
                "input": "page url/name",
            },
        ],
    },
    {
        "id": "web_meta",
        "title": "Сайты и метаданные файлов",
        "desc": "Подходят для своих файлов и своих доменов.",
        "tools": [
            {
                "id": "metadetective",
                "name": "MetaDetective",
                "repo": "https://github.com/franckferman/MetaDetective",
                "purpose": "Вытаскивает метаданные из документов/фото, которые ты сам загрузил.",
                "input": "file",
            },
            {
                "id": "webextractor",
                "name": "WebExtractor",
                "repo": "https://github.com/s-r-e-e-r-a-j/WebExtractor",
                "purpose": "Извлечение публичных элементов страницы (ссылки, emails на сайте, и т.п.).",
                "input": "url",
            },
            {
                "id": "media_search",
                "name": "media-search-engine",
                "repo": "https://github.com/conflict-investigations/media-search-engine",
                "purpose": "Поиск по открытым медиа-источникам (журналистика / фактчек).",
                "input": "query / media",
            },
        ],
    },
    {
        "id": "lab",
        "title": "Учебные стенды",
        "desc": "Симуляции на локальных данных. Не для чужих сайтов.",
        "tools": [
            {
                "id": "sqli_lab",
                "name": "SQLi Lab",
                "repo": "",
                "purpose": "Локальная симуляция Boolean / UNION / time-based / OOB. Учебный стенд.",
                "input": "payload",
                "live": True,
            },
        ],
    },
]
