CATALOG = [
    {
        "id": "username",
        "title": "🔎 Поиск username",
        "desc": "Поиск публичных аккаунтов по никнейму на разных платформах.",
        "tools": [
            {
                "id": "handlehawk",
                "name": "HandleHawk",
                "repo": "https://github.com/C3n7ral051nt4g3ncy/HandleHawk",
                "purpose": "✨ Кросс-платформенный поиск: Reddit, Mastodon, Bluesky, Nostr, PayPal, Snapchat, X/Twitter, BlueSky. Генерирует HTML-отчеты с фото.",
                "input": "username",
                "stars": 142,
                "lang": "Python",
            },
        ],
    },
    {
        "id": "ip_tracking",
        "title": "🌍 Геолокация и трекинг IP",
        "desc": "Анализ и отслеживание IP-адресов с картированием.",
        "tools": [
            {
                "id": "traxosint",
                "name": "TraxOsint",
                "repo": "https://github.com/N0rz3/TraxOsint",
                "purpose": "📍 Полный анализ IP: геолокация, открытые порты, проверка VPN, Pastebin, организация, ISP. Асинхронный, создаёт интерактивные карты.",
                "input": "IP address",
                "stars": 258,
                "lang": "Python",
            },
        ],
    },
    {
        "id": "metadata",
        "title": "📄 Метаданные и веб-анализ",
        "desc": "Извлечение метаданных из документов и веб-сайтов.",
        "tools": [
            {
                "id": "metadetective",
                "name": "MetaDetective",
                "repo": "https://github.com/franckferman/MetaDetective",
                "purpose": "🔍 Извлечение EXIF, авторов, версий ПО, GPS, дат. Веб-скрейпинг PDF/DOCX/IMG. Экспорт HTML/JSON/TXT. Без зависимостей.",
                "input": "файлы или URL",
                "stars": 505,
                "lang": "Python",
            },
            {
                "id": "webcheck",
                "name": "WebCheck-OSINT",
                "repo": "https://github.com/mwakidenis/WebCheck-OSINT",
                "purpose": "🌐 Комплексный анализ: SSL, DNS, TLS, тек. стек, открытые порты, гео, SEO, угрозы, архив.",
                "input": "domain",
                "stars": 166,
                "lang": "TypeScript",
            },
        ],
    },
    {
        "id": "phone",
        "title": "📱 Анализ номеров телефонов",
        "desc": "OSINT по номерам: проверка на соцсетях, информация о номере.",
        "tools": [
            {
                "id": "ignorant",
                "name": "Ignorant",
                "repo": "https://github.com/megadose/ignorant",
                "purpose": "📲 Проверка номера на: Instagram, Snapchat, Amazon БЕЗ алертов. Асинхронно. Модульная архитектура.",
                "input": "phone + country_code",
                "stars": 2000,
                "lang": "Python",
            },
            {
                "id": "phoneinfoga",
                "name": "PhoneInfoga Maltego",
                "repo": "https://github.com/megadose/phoneinfoga-maltego",
                "purpose": "☎️ Информация о номере телефона: оператор, страна, утечки. Интеграция с Maltego для визуализации.",
                "input": "phone",
                "stars": 134,
                "lang": "Python",
            },
        ],
    },
    {
        "id": "email",
        "title": "✉️ Восстановление email",
        "desc": "Восстановление info через 'забыл пароль' на соцсетях.",
        "tools": [
            {
                "id": "quidam",
                "name": "Quidam",
                "repo": "https://github.com/megadose/Quidam",
                "purpose": "🔑 Восстановление email через forgot password: Twitter, Instagram, GitHub. Раскрывает домен + частичный email.",
                "input": "username",
                "stars": 226,
                "lang": "Python",
            },
        ],
    },
    {
        "id": "profiling",
        "title": "👤 Профилирование личности",
        "desc": "Сбор информации о человеке: соцсети, адреса, работа, контакты.",
        "tools": [
            {
                "id": "daprofiler",
                "name": "DaProfiler (архивирован)",
                "repo": "https://github.com/daprofiler/DaProfiler",
                "purpose": "🔎 Сборка личности: адреса, соцсети, emails, телефоны, работа, фото. Requires Python 3.8 + Firefox. ОБРАЗОВАТЕЛЬНО.",
                "input": "name + lastname",
                "stars": 1000,
                "lang": "Python",
                "archived": True,
            },
        ],
    },
    {
        "id": "mapping",
        "title": "🗺️ Картографирование OSINT",
        "desc": "Визуальное органзованизирование информации на карте.",
        "tools": [
            {
                "id": "osint_mapping",
                "name": "OSINT Mapping Tool",
                "repo": "https://github.com/anonymousRAID/OSINT-Mapping-Tool",
                "purpose": "🗺️ Интерактивная карта + граф узлов. Связываем людей, места, события. Сохранение в .osint.json. Локальное хранилище.",
                "input": "interactive research tool",
                "stars": 646,
                "lang": "JavaScript/React",
            },
        ],
    },
    {
        "id": "telegram",
        "title": "✈️ Telegram разведка",
        "desc": "Поиск и анализ Telegram каналов, групп и пользователей.",
        "tools": [
            {
                "id": "telegramdb",
                "name": "TelegramDB",
                "repo": "https://github.com/TelegramDB/TelegramDB",
                "purpose": "Индекс публичных Telegram групп/каналов. Поиск по ключевому слову. Free + Premium поиск с экспортом.",
                "input": "keyword / channel / user_id",
                "stars": 218,
                "lang": "Web Service",
                "blocked": True,
            },
        ],
    },
    {
        "id": "reference",
        "title": "📚 Справочники и шпаргалки",
        "desc": "Коллекции инструментов и методик OSINT.",
        "tools": [
            {
                "id": "notlobi",
                "name": "NotLoBi - OSINT CheatSheet",
                "repo": "https://github.com/NotLoBi/NotLoBi",
                "purpose": "📖 Полная шпаргалка OSINT: все инструменты по категориям (люди, геолокация, скрип, криптовалюты и т.д.)",
                "input": "reference only",
                "stars": 137,
                "lang": "Markdown",
                "reference": True,
            },
        ],
    },
    {
        "id": "lab",
        "title": "🧪 Учебные стенды",
        "desc": "Симуляции на локальных данных. Для обучения.",
        "tools": [
            {
                "id": "sqli_lab",
                "name": "SQLi Lab",
                "repo": "",
                "purpose": "Локальная симуляция Boolean / UNION / time-based / OOB SQL Injection. Учебный стенд.",
                "input": "payload",
                "stars": 0,
                "lang": "Internal",
                "live": True,
            },
        ],
    },
]
