"""
Каталог OSINT-инструментов с GitHub, расширенными возможностями Telegram-разведки,
GeoINT, поиском по соцсетям, инструкциями и запуском в WebApp.
"""

CATALOG = [   {   'desc': 'Самые мощные умные инструменты: составление досье через нейросети, трекер сна и активности, проверка '
                'чистоты крипты и распознавание лиц.',
        'id': 'killer_monetization',
        'title': '💎 AI-Профайлинг, Шпион онлайна & Проверка на обман',
        'tools': [   {   'id': 'ai_detective_profiler',
                         'input': 'никнейм, имя или ссылка (например, durov)',
                         'install_guide': {   'docker': '# Работает автономно в WebApp',
                                              'git': '# Встроенный в систему аналитический AI-модуль',
                                              'notes': 'Анализирует профили, активность, связанные почты и формирует '
                                                       'подробный отчет.',
                                              'pip_or_pkg': 'pip install google-genai httpx',
                                              'usage': 'Введите никнейм человека для генерации полного досье с '
                                                       'выводами AI'},
                         'launch': {'action': 'scan_ai_profiler', 'label': '⚡ Сформировать AI Досье', 'type': 'api'},
                         'name': '🧠 AI Детектив: Полное досье и проверка на обман (Scam Score)',
                         'purpose': '🎯 Собирает информацию о человеке со всех доступных сервисов и с помощью нейросети '
                                    'составляет психологический портрет, оценивает вероятность обмана/фейка (Scam '
                                    'Score 0-100%) и находит скрытые контакты.',
                         'repo': 'https://github.com/sherlock-project/sherlock',
                         'scan_type': 'ai_profiler',
                         'web_runnable': True,
                         'web_url': ''},
                     {   'id': 'tg_activity_tracker',
                         'input': '@username (или два @user1, @user2 для поиска тайной связи)',
                         'install_guide': {   'docker': '# Встроенный сервис',
                                              'git': '# Анализатор активности и временных меток',
                                              'notes': 'Помогает узнать реальный режим дня человека и часовой пояс.',
                                              'pip_or_pkg': 'pip install httpx asyncio',
                                              'usage': 'Введите один юзернейм или два через запятую для проверки '
                                                       'тайной связи'},
                         'launch': {   'action': 'scan_activity_tracker',
                                       'label': '⚡ Узнать график сна и онлайна',
                                       'type': 'api'},
                         'name': '⏱️ Шпион онлайна и сна в Telegram (Трекер активности)',
                         'purpose': '📊 Показывает суточный график активности человека в Telegram: когда он '
                                    'просыпается, когда ложится спать и в какие часы сидит в сети. Функция сравнения '
                                    'выявляет тайное общение двух людей, если они заходят онлайн одновременно.',
                         'repo': 'https://github.com/TelegramDB/TelegramDB',
                         'scan_type': 'activity_tracker',
                         'web_runnable': True,
                         'web_url': ''},
                     {   'id': 'crypto_aml_auditor',
                         'input': 'адрес кошелька (BTC, ETH, USDT TRC-20, SOL)',
                         'install_guide': {   'docker': '# Встроенный сервис',
                                              'git': '# Модуль проверки чистоты транзакций',
                                              'notes': 'Помогает избежать блокировки счета на биржах Binance, Bybit и '
                                                       'других.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите адрес кошелька перед приемом оплаты или переводом'},
                         'launch': {   'action': 'scan_crypto_aml',
                                       'label': '⚡ Проверить чистоту кошелька',
                                       'type': 'api'},
                         'name': '🚨 Проверка криптокошелька на чистоту и мошенников (AML Риск)',
                         'purpose': '🛡️ Проверяет адреса USDT, Bitcoin, Ethereum и Solana на связь с кражами, '
                                    'даркнетом, миксерами и санкциями. Показывает шкалу риска (0-100%), чтобы ваши '
                                    'деньги не заблокировали на бирже.',
                         'repo': 'https://github.com/bitcoin/bitcoin',
                         'scan_type': 'crypto_aml',
                         'web_runnable': True,
                         'web_url': 'https://blockchair.com/'},
                     {   'id': 'face_search_ai',
                         'input': 'загрузите фото лица (JPG / PNG / WebP)',
                         'install_guide': {   'docker': '# Встроенный в WebApp',
                                              'git': '# Нейросетевой модуль биометрического анализа',
                                              'notes': 'Помогает разоблачить мошенников на сайтах знакомств и в '
                                                       'Telegram.',
                                              'pip_or_pkg': 'pip install Pillow numpy',
                                              'usage': 'Загрузите фото для поиска совпадений и выявления фейковых '
                                                       'аватарок'},
                         'launch': {   'action': 'scan_face_search',
                                       'label': '⚡ Найти по фото и проверить Deepfake',
                                       'type': 'api'},
                         'name': '👤 Поиск человека по фото лица и проверка на фейк (Face AI)',
                         'purpose': '🔍 Находит одинаковые и похожие лица среди аватарок в соцсетях и Telegram, а также '
                                    'мгновенно распознает, сгенерировано ли фото нейросетью (Deepfake / не существует '
                                    'ли такого человека в реальности).',
                         'repo': 'https://github.com/ageitgey/face_recognition',
                         'scan_type': 'face_search',
                         'web_runnable': True,
                         'web_url': ''},
                     {   'id': 'digital_hygiene_audit',
                         'input': 'ваша почта, телефон или никнейм',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': '# Модуль проверки собственной безопасности',
                                              'notes': 'Формирует понятный чек-лист действий для защиты своих '
                                                       'аккаунтов.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите свою почту или номер для проверки наличия в базах '
                                                       'утечек'},
                         'launch': {'action': 'scan_breach_audit', 'label': '⚡ Проверить свои утечки', 'type': 'api'},
                         'name': '🛡️ Проверка утечек своих данных (Аудит цифровой безопасности)',
                         'purpose': '🔐 Проверяет вашу личную почту, телефон или никнейм по базам утекших паролей. '
                                    'Показывает, где именно утекли ваши данные, насколько уязвим аккаунт, и дает '
                                    'понятные советы по защите.',
                         'repo': 'https://github.com/sherlock-project/sherlock',
                         'scan_type': 'breach_audit',
                         'web_runnable': True,
                         'web_url': ''},
                     {   'id': 'target_monitor_alerts',
                         'input': '@username, ссылка на канал или адрес кошелька',
                         'install_guide': {   'docker': '# Работает в фоновом режиме',
                                              'git': '# Фоновый робот мониторинга целей',
                                              'notes': 'Уведомления приходят прямо в личные сообщения Telegram-бота.',
                                              'pip_or_pkg': 'pip install aiogram httpx',
                                              'usage': 'Укажите цель для добавления в список постоянного наблюдения'},
                         'launch': {'action': 'subscribe_target_alerts', 'label': '⚡ Включить слежку', 'type': 'api'},
                         'name': '🔔 Умная слежка и уведомления в Telegram (Target Monitor)',
                         'purpose': '📡 Ставит нужный профиль Telegram, канал или криптокошелек на круглосуточное '
                                    'наблюдение. Как только цель сменит фото, описание, никнейм или переведет '
                                    'криптовалюту — бот сразу пришлет вам сообщение.',
                         'repo': 'https://github.com/TelegramDB/TelegramDB',
                         'scan_type': 'target_alerts',
                         'web_runnable': True,
                         'web_url': ''}]},
    {   'desc': 'Инструменты для проверки Telegram аккаунтов, каналов, поиска реальных владельцев фейков и истории '
                'изменений.',
        'id': 'telegram_osint',
        'title': '✈️ Telegram Разведка & Анализ профилей',
        'tools': [   {   'id': 'sockpuppet_attribution',
                         'input': 'юзернейм (@username) или Telegram ID фейка',
                         'install_guide': {   'docker': '# Встроен в WebApp',
                                              'git': '# Аналитический движок поиска связей',
                                              'notes': 'Помогает понять, кто на самом деле стоит за анонимным '
                                                       'профилем.',
                                              'pip_or_pkg': 'pip install httpx beautifulsoup4',
                                              'usage': 'Введите юзернейм подозрительного аккаунта для поиска основы'},
                         'launch': {'action': 'scan_attribution', 'label': '⚡ Найти основу фейка', 'type': 'api'},
                         'name': '🕵️ Поиск реального владельца фейка / вирта в Telegram (Attribution)',
                         'purpose': '🎯 Определяет основной (реальный) аккаунт человека, если он пишет с подставного, '
                                    'второго или купленного профиля Telegram, сопоставляя историю никнеймов, ID и '
                                    'цифровые следы.',
                         'repo': 'https://github.com/sherlock-project/sherlock',
                         'scan_type': 'attribution',
                         'web_runnable': True,
                         'web_url': 'https://t.me/'},
                     {   'id': 'tg_inspector',
                         'input': 'юзернейм (например, @durov) или Telegram ID',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный веб-сканер Telegram',
                                              'notes': 'Позволяет быстро получить публичные данные без авторизации.',
                                              'pip_or_pkg': 'pip install httpx beautifulsoup4',
                                              'usage': 'Введите юзернейм аккаунта в поле выше'},
                         'launch': {'action': 'scan_telegram', 'label': '⚡ Проверить профиль Telegram', 'type': 'api'},
                         'name': '🔍 Досье на Telegram профиль и дата создания (TG Inspector)',
                         'purpose': '🔎 Мгновенно показывает открытые данные любого пользователя или канала: настоящее '
                                    'имя, Bio, аватарку в высоком качестве, статус бота и примерный год создания '
                                    'аккаунта по его ID.',
                         'repo': 'https://github.com/TelegramDB/TelegramDB',
                         'scan_type': 'telegram',
                         'web_runnable': True,
                         'web_url': 'https://t.me/'},
                     {   'id': 'telepathy',
                         'input': 'ссылка на Telegram канал или чат',
                         'install_guide': {   'docker': 'docker run -it telepathy-osint',
                                              'git': 'git clone https://github.com/jordanwildon/Telepathy.git',
                                              'notes': 'Позволяет исследовать структуру и аудиторию публичных '
                                                       'сообществ.',
                                              'pip_or_pkg': 'pip3 install telepathy-osint',
                                              'usage': 'telepathy -t @target_channel --export csv'},
                         'launch': {   'href': 'https://github.com/jordanwildon/Telepathy',
                                       'label': '📖 Открыть Telepathy на GitHub',
                                       'type': 'url'},
                         'name': '📊 Анализатор Telegram каналов и чатов (Telepathy)',
                         'purpose': '📈 Выгружает списки участников групп, карту пересылок постов, историю упоминаний и '
                                    'показывает, с какими другими каналами связан исследуемый ресурс.',
                         'repo': 'https://github.com/jordanwildon/Telepathy',
                         'web_runnable': False,
                         'web_url': 'https://github.com/jordanwildon/Telepathy'},
                     {   'id': 'telegramdb',
                         'input': 'ключевое слово, фраза или никнейм',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': '# Общедоступный веб-сервис',
                                              'notes': 'Помогает найти скрытые тематические группы и сообщества.',
                                              'pip_or_pkg': '# Доступен через онлайн-интерфейс',
                                              'usage': 'Открыть сайт https://telegramdb.org/ и ввести слово для '
                                                       'поиска'},
                         'launch': {   'href': 'https://telegramdb.org/',
                                       'label': '🌐 Открыть TelegramDB Онлайн',
                                       'type': 'url'},
                         'name': '🌐 Глобальный поисковик по чатам и сообщениям (TelegramDB)',
                         'purpose': '🔎 Ищет публичные группы, каналы и сообщения по любым ключевым словам, фразам или '
                                    'темам во всемирной базе Telegram.',
                         'repo': 'https://github.com/TelegramDB/TelegramDB',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://telegramdb.org/'},
                     {   'id': 'tgstat',
                         'input': 'юзернейм канала (например, @breakingmash)',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': '# Официальный аналитический портал',
                                              'notes': 'Самый подробный каталог статистики каналов в СНГ.',
                                              'pip_or_pkg': '# Открытый веб-сервис',
                                              'usage': 'Открыть сайт https://tgstat.ru/ и ввести @канал'},
                         'launch': {'href': 'https://tgstat.ru/', 'label': '🌐 Открыть TGStat Онлайн', 'type': 'url'},
                         'name': '📈 Аналитика и история Telegram каналов (TGStat)',
                         'purpose': '📊 Показывает полную статистику любого канала: реальный прирост подписчиков, '
                                    'охваты постов, историю смены названий и удаленные публикации.',
                         'repo': 'https://tgstat.ru/',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://tgstat.ru/'}]},
    {   'desc': 'Необычные методы разведки: определение времени съемки по тени солнца, просмотр старых удаленных '
                'страниц и спутниковые снимки.',
        'id': 'amazing_osint',
        'title': '🌟 GeoINT, Спутники & Фото-детектив',
        'tools': [   {   'id': 'suncalc',
                         'input': 'город, координаты или дата съемки',
                         'install_guide': {   'docker': '# Работает в браузере',
                                              'git': 'git clone https://github.com/mourner/suncalc.git',
                                              'notes': 'Ключевой инструмент международных расследователей для проверки '
                                                       'подлинности фото.',
                                              'pip_or_pkg': 'npm install suncalc',
                                              'usage': 'Открыть сайт https://suncalc.org, указать точку на карте и '
                                                       'сопоставить тень со снимка'},
                         'launch': {'href': 'https://suncalc.org/', 'label': '🌐 Открыть SunCalc Онлайн', 'type': 'url'},
                         'name': '☀️ Определение времени съемки по тени солнца (SunCalc)',
                         'purpose': '🕒 Позволяет узнать точное время и дату, когда была сделана фотография на улице, '
                                    'рассчитывая положение солнца и направление тени от зданий и предметов.',
                         'repo': 'https://github.com/mourner/suncalc',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://suncalc.org/'},
                     {   'id': 'wayback',
                         'input': 'ссылка на сайт или профиль (например, twitter.com/user)',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': '# Официальный архив интернета',
                                              'notes': 'Позволяет восстановить удаленный аккаунт или старые аватарки и '
                                                       'контакты.',
                                              'pip_or_pkg': 'pip install waybackpy',
                                              'usage': 'Ввести ссылку на страницу для просмотра ее копий за прошлые '
                                                       'годы'},
                         'launch': {   'href': 'https://web.archive.org/',
                                       'label': '🌐 Открыть Wayback Machine',
                                       'type': 'url'},
                         'name': '🏛️ Машина времени сайтов: просмотр удаленного (Wayback Machine)',
                         'purpose': '⏳ Показывает, как выглядел любой сайт, страница или профиль в соцсетях в прошлом. '
                                    'Позволяет прочитать удаленные посты, старые контакты и сохраненные копии страниц '
                                    'с 1996 года.',
                         'repo': 'https://github.com/internetarchive/wayback',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://web.archive.org/'},
                     {   'id': 'overpass_turbo',
                         'input': 'детали местности или фильтры карты',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': 'git clone https://github.com/tyrasd/overpass-turbo.git',
                                              'notes': 'Позволяет отыскать точные координаты места съемки по элементам '
                                                       'пейзажа.',
                                              'pip_or_pkg': '# Онлайн песочница',
                                              'usage': 'Открыть сайт https://overpass-turbo.eu/ и запустить фильтрацию '
                                                       'по элементам карты'},
                         'launch': {   'href': 'https://overpass-turbo.eu/',
                                       'label': '🌐 Открыть Overpass Turbo',
                                       'type': 'url'},
                         'name': '📍 Поиск места по деталям на карте (Overpass Turbo)',
                         'purpose': '🗺️ Находит точные координаты локации по обрывкам деталей: например, если на фото '
                                    'видно трамвайные пути рядом с кирпичной башней и аптекой.',
                         'repo': 'https://github.com/tyrasd/overpass-turbo',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://overpass-turbo.eu/'},
                     {   'id': 'zoom_earth',
                         'input': 'город или координаты',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': '# Спутниковая платформа',
                                              'notes': 'Позволяет увидеть актуальное состояние местности из космоса.',
                                              'pip_or_pkg': '# Онлайн интерфейс',
                                              'usage': 'Открыть сайт https://zoom.earth/ для просмотра снимков со '
                                                       'спутников NASA'},
                         'launch': {   'href': 'https://zoom.earth/',
                                       'label': '🌐 Открыть Zoom Earth Онлайн',
                                       'type': 'url'},
                         'name': '🛰️ Спутниковая карта Земли в реальном времени (Zoom Earth)',
                         'purpose': '🌍 Показывает свежие спутниковые снимки планеты высокого разрешения, погоду, '
                                    'пожары и штормы, обновляясь каждые 10-15 минут.',
                         'repo': 'https://zoom.earth/',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://zoom.earth/'}]},
    {   'desc': 'Быстрый поиск человека и его аккаунтов по псевдониму на сотнях сайтов, форумов и соцсетей.',
        'id': 'username_osint',
        'title': '🔍 Поиск человека по никнеймам (750+ баз)',
        'tools': [   {   'id': 'sherlock',
                         'input': 'никнейм (например, alex_pro)',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный в WebApp скоростной движок',
                                              'notes': 'Опрашивает 750+ проверенных мировых баз параллельно за пару '
                                                       'секунд.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите никнейм цели и нажмите «Сканировать»'},
                         'launch': {'action': 'scan_username', 'label': '⚡ Найти все аккаунты в WebApp', 'type': 'api'},
                         'name': '⚡ Поиск человека по никнейму на 750+ сайтах (Sherlock)',
                         'purpose': '🔍 Мгновенно проверяет один никнейм сразу на сотнях платформ (Telegram, GitHub, '
                                    'VK, Steam, Reddit, TikTok, Twitch, Habr и др.) и дает прямые кликабельные ссылки '
                                    'на найденные страницы.',
                         'repo': 'https://github.com/sherlock-project/sherlock',
                         'scan_type': 'username',
                         'web_runnable': True,
                         'web_url': 'https://sherlock-project.github.io/'},
                     {   'id': 'maigret',
                         'input': 'никнейм пользователя',
                         'install_guide': {   'docker': 'docker run --rm -it soxoj/maigret <username>',
                                              'git': 'git clone https://github.com/soxoj/maigret.git',
                                              'notes': 'Генерирует наглядные отчеты со всеми найденными ссылками и '
                                                       'фото.',
                                              'pip_or_pkg': 'pip3 install maigret',
                                              'usage': 'Введите никнейм для проверки расширенной базы сервисов'},
                         'launch': {'action': 'scan_username', 'label': '⚡ Запустить поиск Maigret', 'type': 'api'},
                         'name': '📋 Подробный сбор досье по никнейму (Maigret 3000+ баз)',
                         'purpose': '📑 Глубокий поиск по более чем 3000 сайтам: извлекает имена, аватарки, интересы и '
                                    'автоматически строит сводный отчет по человеку.',
                         'repo': 'https://github.com/soxoj/maigret',
                         'scan_type': 'username',
                         'web_runnable': True,
                         'web_url': 'https://maigret.readthedocs.io/'},
                     {   'id': 'blackbird',
                         'input': 'никнейм',
                         'install_guide': {   'docker': 'docker run -p 9797:9797 blackbird',
                                              'git': 'git clone https://github.com/p1ngul1n0/blackbird',
                                              'notes': 'Использует современные алгоритмы исключения ложных '
                                                       'срабатываний.',
                                              'pip_or_pkg': 'pip3 install -r requirements.txt',
                                              'usage': 'Введите никнейм для скоростной проверки аккаунтов'},
                         'launch': {'action': 'scan_username', 'label': '⚡ Быстрый поиск в WebApp', 'type': 'api'},
                         'name': '🚀 Скоростной чекер никнеймов (Blackbird)',
                         'purpose': '⚡ Быстрая проверка присутствия ника в соцсетях с удобным интерфейсом и '
                                    'фильтрацией только реально существующих страниц.',
                         'repo': 'https://github.com/p1ngul1n0/blackbird',
                         'scan_type': 'username',
                         'web_runnable': True,
                         'web_url': 'https://github.com/p1ngul1n0/blackbird'},
                     {   'id': 'social_analyzer',
                         'input': 'никнейм или имя профиля',
                         'install_guide': {   'docker': 'docker run -p 9005:9005 -it qeeqbox/social-analyzer',
                                              'git': 'git clone https://github.com/qeeqbox/social-analyzer.git',
                                              'notes': 'Позволяет просматривать профили даже при блокировках сайтов.',
                                              'pip_or_pkg': 'pip3 install social-analyzer',
                                              'usage': 'python3 app.py --username target_user'},
                         'launch': {   'href': 'https://github.com/qeeqbox/social-analyzer',
                                       'label': '📖 Открыть репозиторий на GitHub',
                                       'type': 'url'},
                         'name': '📸 Анализ страниц с автоматическими скриншотами (Social-Analyzer)',
                         'purpose': '🖼️ Не просто находит аккаунты человека, но и автоматически делает скриншоты '
                                    'найденных страниц для удобного просмотра без перехода по сайтам.',
                         'repo': 'https://github.com/qeeqbox/social-analyzer',
                         'web_runnable': False,
                         'web_url': 'https://github.com/qeeqbox/social-analyzer'},
                     {   'id': 'whatsmyname',
                         'input': 'никнейм',
                         'install_guide': {   'docker': '# Доступно через https://whatsmyname.app/',
                                              'git': 'git clone https://github.com/WebBreacher/WhatsMyName.git',
                                              'notes': 'База WhatsMyName используется в большинстве профессиональных '
                                                       'OSINT-систем.',
                                              'pip_or_pkg': '# Доступно онлайн',
                                              'usage': 'Открыть сайт https://whatsmyname.app/ и ввести никнейм'},
                         'launch': {   'href': 'https://whatsmyname.app/',
                                       'label': '🌐 Открыть WhatsMyName WebApp',
                                       'type': 'url'},
                         'name': '🌐 Глобальный каталог поиска по именам (WhatsMyName)',
                         'purpose': '🔍 Всемирно признанная открытая база проверочных шаблонов для мгновенного '
                                    'нахождения учетных записей по всему интернету.',
                         'repo': 'https://github.com/WebBreacher/WhatsMyName',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://whatsmyname.app/'}]},
    {   'desc': 'Инструменты для извлечения скрытых телефонов, почт, привязок и анализа профилей Instagram, VK, '
                'TikTok, X/Twitter и Google.',
        'id': 'social_google_instagram',
        'title': '📱 Google, Instagram & Социальные сети',
        'tools': [   {   'id': 'ghunt',
                         'input': 'почта Gmail (например, target@gmail.com)',
                         'install_guide': {   'docker': 'docker run -it ghunt email target@gmail.com',
                                              'git': 'git clone https://github.com/mxrch/GHunt.git',
                                              'notes': 'Помогает восстановить перемещения человека по его отзывам на '
                                                       'Google Картах.',
                                              'pip_or_pkg': 'pip install ghunt',
                                              'usage': 'ghunt email target@gmail.com'},
                         'launch': {   'href': 'https://github.com/mxrch/GHunt',
                                       'label': '📖 Открыть GHunt на GitHub',
                                       'type': 'url'},
                         'name': '📧 Разведка по почте Google / Gmail (GHunt)',
                         'purpose': '🔍 Показывает скрытую информацию о владельце почты Gmail: его настоящее имя, '
                                    'отзывы и отметки на Google Картах (где он бывал), канал на YouTube и дату '
                                    'создания профиля.',
                         'repo': 'https://github.com/mxrch/GHunt',
                         'web_runnable': False,
                         'web_url': 'https://github.com/mxrch/GHunt'},
                     {   'id': 'instaloader',
                         'input': 'юзернейм Instagram (например, travel_blogger)',
                         'install_guide': {   'docker': 'docker run --rm -v $(pwd):/data instaloader/instaloader '
                                                        'profile <target>',
                                              'git': 'git clone https://github.com/instaloader/instaloader.git',
                                              'notes': 'Дает прямые ссылки на просмотр историй и постов без '
                                                       'авторизации.',
                                              'pip_or_pkg': 'pip3 install instaloader',
                                              'usage': 'Введите ник Instagram для анонимного просмотра и ссылок на '
                                                       'просмотрщики'},
                         'launch': {'action': 'scan_universal', 'label': '⚡ Анализировать Instagram', 'type': 'api'},
                         'name': '📸 Сохранение фото и историй Instagram (Instaloader)',
                         'purpose': '📥 Позволяет сохранять публикации, истории и видео из Instagram вместе с '
                                    'геометками (где было снято фото), точным временем и комментариями.',
                         'repo': 'https://github.com/instaloader/instaloader',
                         'scan_type': 'cli_tool',
                         'web_runnable': True,
                         'web_url': 'https://instaloader.github.io/'},
                     {   'id': 'osintgram',
                         'input': 'юзернейм Instagram',
                         'install_guide': {   'docker': 'docker run --rm -it osintgram <target>',
                                              'git': 'git clone https://github.com/Datalux/Osintgram.git',
                                              'notes': 'Позволяет получить телефон, почту и список отметок человека на '
                                                       'фото.',
                                              'pip_or_pkg': 'pip3 install -r requirements.txt',
                                              'usage': 'python3 main.py <target_username>'},
                         'launch': {'action': 'scan_universal', 'label': '⚡ Запустить Osintgram', 'type': 'api'},
                         'name': '🕵️ Терминал Instagram-расследований (Osintgram)',
                         'purpose': '🔎 Извлекает списки подписчиков, номера телефонов и почты из описаний, геометки '
                                    'всех фотографий и историю комментариев пользователя.',
                         'repo': 'https://github.com/Datalux/Osintgram',
                         'scan_type': 'cli_tool',
                         'web_runnable': True,
                         'web_url': 'https://github.com/Datalux/Osintgram'},
                     {   'id': 'toutatis',
                         'input': 'юзернейм Instagram',
                         'install_guide': {   'docker': 'docker run -it toutatis',
                                              'git': 'git clone https://github.com/megadose/toutatis.git',
                                              'notes': 'Помогает сопоставить профиль Instagram с известным номером '
                                                       'телефона.',
                                              'pip_or_pkg': 'pip3 install toutatis',
                                              'usage': 'toutatis -u <username>'},
                         'launch': {'action': 'scan_universal', 'label': '⚡ Узнать телефон и почту', 'type': 'api'},
                         'name': '📞 Поиск номера телефона и почты из Instagram (Toutatis)',
                         'purpose': '📱 Узнает скрытые символы привязанного к Instagram номера телефона (+7***42) и '
                                    'частичный адрес почты через официальные формы восстановления доступа.',
                         'repo': 'https://github.com/megadose/toutatis',
                         'scan_type': 'cli_tool',
                         'web_runnable': True,
                         'web_url': 'https://github.com/megadose/toutatis'},
                     {   'id': 'instagram_followers_parser',
                         'input': 'ссылка на профиль Instagram',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': 'git clone '
                                                     'https://github.com/VladiStep/instagram_followers_parser.git',
                                              'notes': 'Автоматически прокручивает список и сохраняет всех '
                                                       'подписчиков.',
                                              'pip_or_pkg': '# Браузерный скрипт',
                                              'usage': 'Вставить код скрипта в консоль браузера на странице '
                                                       'подписчиков'},
                         'launch': {   'href': 'https://github.com/VladiStep/instagram_followers_parser',
                                       'label': '📖 Открыть скрипт на GitHub',
                                       'type': 'url'},
                         'name': '👥 Выгрузка списка подписчиков страницы Instagram',
                         'purpose': '⚡ Удобный скрипт для быстрой выгрузки всех подписчиков и подписок любого '
                                    'открытого профиля Instagram в удобный список.',
                         'repo': 'https://github.com/VladiStep/instagram_followers_parser',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://github.com/VladiStep/instagram_followers_parser'},
                     {   'id': 'vk_recon',
                         'input': 'короткий адрес или ID ВКонтакте (например, durov или id1)',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный веб-сканер VK',
                                              'notes': 'Генерирует поисковые запросы по стене, фото и архивным копиям.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите никнейм или ID страницы (например, durov или id12345)'},
                         'launch': {'action': 'scan_username', 'label': '⚡ Анализ страницы ВКонтакте', 'type': 'api'},
                         'name': '🌐 Поиск скрытых данных ВКонтакте (VK Recon)',
                         'purpose': '🔎 Находит скрытых друзей, старые записи на стене, закрытые альбомы, привязанные '
                                    'города и историю изменения страниц ВКонтакте.',
                         'repo': 'https://github.com/sherlock-project/sherlock',
                         'scan_type': 'username',
                         'web_runnable': True,
                         'web_url': 'https://vk.com/'},
                     {   'id': 'tiktok_osint',
                         'input': 'юзернейм TikTok (например, @tiktok_star)',
                         'install_guide': {   'docker': 'docker run -it drawrowfly/tiktok-scraper user <username>',
                                              'git': 'git clone https://github.com/drawrowfly/tiktok-scraper.git',
                                              'notes': 'Позволяет скачать аватар в полном размере и узнать скрытый '
                                                       'SecUID.',
                                              'pip_or_pkg': 'npm install -g tiktok-scraper',
                                              'usage': 'Введите @юзернейм TikTok для проверки'},
                         'launch': {'action': 'scan_username', 'label': '⚡ Проверить профиль TikTok', 'type': 'api'},
                         'name': '🎵 Сбор данных профиля TikTok (TikTok OSINT)',
                         'purpose': '📱 Извлекает скрытый числовой ID автора, аватарку в максимальном качестве, дату '
                                    'создания аккаунта и список популярных хэштегов.',
                         'repo': 'https://github.com/drawrowfly/tiktok-scraper',
                         'scan_type': 'username',
                         'web_runnable': True,
                         'web_url': 'https://www.tiktok.com/'}]},
    {   'desc': 'Инструменты для исследования сайтов, проверки IP, поддоменов, защиты от утечек DNS и поиска утекших '
                'ключей.',
        'id': 'web_infra_secrets',
        'title': '🌐 Сайты, Домены, IP & MyIP Toolbox',
        'tools': [   {   'id': 'myip_toolbox',
                         'input': 'IP-адрес или домен (или оставьте пустым для проверки своего IP)',
                         'install_guide': {   'docker': 'docker run -d -p 18966:18966 jason5ng32/myip:latest',
                                              'git': 'git clone https://github.com/jason5ng32/MyIP.git',
                                              'notes': 'Позволяет убедиться, что ваш реальный IP-адрес надежно скрыт '
                                                       'при использовании VPN/прокси.',
                                              'pip_or_pkg': 'npm install && npm run build',
                                              'usage': 'Введите IP или домен для проверки геолокации, автономной '
                                                       'системы и утечек DNS'},
                         'launch': {'action': 'scan_myip', 'label': '⚡ Анализ MyIP в WebApp', 'type': 'api'},
                         'name': '🌐 Комплексный анализ IP & Проверка утечки DNS (MyIP Toolbox)',
                         'purpose': '🛡️ Показывает ваш реальный IP, страну, город, провайдера, проверяет, не утекает '
                                    'ли реальный адрес через DNS/WebRTC, и тестирует скорость соединения.',
                         'repo': 'https://github.com/jason5ng32/MyIP',
                         'scan_type': 'myip',
                         'web_runnable': True,
                         'web_url': 'https://ipcheck.ing/'},
                     {   'id': 'photon',
                         'input': 'ссылка на сайт (например, site.com)',
                         'install_guide': {   'docker': 'docker run -it photon -u target.com',
                                              'git': 'git clone https://github.com/s0md3v/Photon.git',
                                              'notes': 'Быстро собирает все контакты и документы с целевого ресурса.',
                                              'pip_or_pkg': 'pip3 install -r requirements.txt',
                                              'usage': 'python3 photon.py -u https://target.com --keys --export'},
                         'launch': {   'href': 'https://github.com/s0md3v/Photon',
                                       'label': '📖 Открыть Photon на GitHub',
                                       'type': 'url'},
                         'name': '🕷️ Быстрый сборщик контактов с сайта (Photon Crawler)',
                         'purpose': '🕸️ Автоматически обходит любой сайт и находит на нем все спрятанные email-адреса, '
                                    'телефоны, ссылки на соцсети и скрытые файлы.',
                         'repo': 'https://github.com/s0md3v/Photon',
                         'web_runnable': False,
                         'web_url': 'https://github.com/s0md3v/Photon'},
                     {   'id': 'trufflehog',
                         'input': 'ссылка на репозиторий GitHub или сайт',
                         'install_guide': {   'docker': 'docker run -it trufflesecurity/trufflehog:latest',
                                              'git': 'git clone https://github.com/trufflesecurity/trufflehog.git',
                                              'notes': 'Автоматически проверяет, работают ли найденные ключи.',
                                              'pip_or_pkg': 'curl -sSfL '
                                                            'https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh '
                                                            '| sh',
                                              'usage': 'trufflehog github --repo https://github.com/target/repo'},
                         'launch': {   'href': 'https://github.com/trufflesecurity/trufflehog',
                                       'label': '📖 Открыть TruffleHog на GitHub',
                                       'type': 'url'},
                         'name': '🔑 Поиск забытых паролей и API-ключей (TruffleHog)',
                         'purpose': '🔐 Сканирует сайты и открытые репозитории с кодом, находя случайно опубликованные '
                                    'пароли, секретные ключи доступа и токены.',
                         'repo': 'https://github.com/trufflesecurity/trufflehog',
                         'web_runnable': False,
                         'web_url': 'https://trufflesecurity.com/'},
                     {   'id': 'finalrecon',
                         'input': 'адрес сайта или домен (например, example.com)',
                         'install_guide': {   'docker': 'docker run -it finalrecon --full https://target.com',
                                              'git': 'git clone https://github.com/thewhiteh4t/FinalRecon.git',
                                              'notes': 'Генерирует аккуратный сводный отчет обо всей инфраструктуре '
                                                       'сайта.',
                                              'pip_or_pkg': 'pip3 install -r requirements.txt',
                                              'usage': 'python3 finalrecon.py --full https://target.com'},
                         'launch': {   'href': 'https://github.com/thewhiteh4t/FinalRecon',
                                       'label': '📖 Открыть FinalRecon на GitHub',
                                       'type': 'url'},
                         'name': '🎯 Экспресс-проверка сайта: сервер, защита, порты (FinalRecon)',
                         'purpose': '🖥️ За считанные секунды собирает полное досье на сайт: где физически стоит '
                                    'сервер, какой у него сертификат безопасности, кто владелец и какие порты открыты.',
                         'repo': 'https://github.com/thewhiteh4t/FinalRecon',
                         'web_runnable': False,
                         'web_url': 'https://github.com/thewhiteh4t/FinalRecon'},
                     {   'id': 'webcheck',
                         'input': 'домен сайта',
                         'install_guide': {   'docker': 'docker run -p 3000:3000 lissy93/web-check',
                                              'git': 'git clone https://github.com/Lissy93/web-check.git',
                                              'notes': 'Показывает подробный технический паспорт сайта с графиками.',
                                              'pip_or_pkg': 'npm install && npm run build',
                                              'usage': 'Доступен публичный облачный сервис https://web-check.xyz/ без '
                                                       'установки'},
                         'launch': {   'href': 'https://web-check.xyz/',
                                       'label': '🌐 Открыть Web-Check Онлайн',
                                       'type': 'url'},
                         'name': '📊 Наглядный онлайн-аудит любого сайта (Web-Check)',
                         'purpose': '🌐 Красивая интерактивная панель, показывающая все технические данные сайта: '
                                    'хостинг, страну расположения, безопасность и историю домена.',
                         'repo': 'https://github.com/Lissy93/web-check',
                         'scan_type': 'domain',
                         'web_runnable': True,
                         'web_url': 'https://web-check.xyz/'},
                     {   'id': 'subfinder',
                         'input': 'домен организации (например, company.com)',
                         'install_guide': {   'docker': 'docker run projectdiscovery/subfinder -d example.com',
                                              'git': 'git clone https://github.com/projectdiscovery/subfinder.git',
                                              'notes': 'Пассивный поиск без прямой нагрузки на целевой сервер.',
                                              'pip_or_pkg': 'go install '
                                                            'github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest',
                                              'usage': 'Введите домен в поле выше для автоматического поиска '
                                                       'поддоменов'},
                         'launch': {'action': 'scan_domain', 'label': '⚡ Найти все поддомены', 'type': 'api'},
                         'name': '🔍 Поиск всех поддоменов сайта (Subfinder)',
                         'purpose': '🔎 Находит скрытые, тестовые и внутренние страницы организации (например, '
                                    'admin.site.com, dev.site.com, mail.site.com).',
                         'repo': 'https://github.com/projectdiscovery/subfinder',
                         'scan_type': 'domain',
                         'web_runnable': True,
                         'web_url': 'https://github.com/projectdiscovery/subfinder'}]},
    {   'desc': 'Инструменты для построения карт расследования, визуализации связей людей и готовые матрицы из 70+ '
                'открытых источников.',
        'id': 'mapping_investigation',
        'title': '🗺️ Legendary OSINT, Графы связей & Фреймворки',
        'tools': [   {   'id': 'legendary_osint',
                         'input': 'любая цель: никнейм, телефон, почта, имя или сайт',
                         'install_guide': {   'docker': '# Встроен в панель WebApp',
                                              'git': 'git clone https://github.com/K2SOsint/Legendary_OSINT.git',
                                              'notes': 'Объединяет поиск людей, транспорта, телефонных книг, '
                                                       'документов и утечек.',
                                              'pip_or_pkg': 'pip install rich questionary requests',
                                              'usage': 'Введите цель для генерации готовых поисковых сканеров по 70+ '
                                                       'реестрам'},
                         'launch': {   'action': 'scan_legendary',
                                       'label': '⚡ Запустить поиск в 70+ базах',
                                       'type': 'api'},
                         'name': '🌟 Легендарная матрица поиска людей и утечек (Legendary OSINT 70+ баз)',
                         'purpose': '🔥 Универсальный комбайн по 70+ проверенным источникам: мгновенно ищет человека по '
                                    'имени, телефону, email, никнейму, автомобильным номерам или сайту.',
                         'repo': 'https://github.com/K2SOsint/Legendary_OSINT',
                         'scan_type': 'legendary',
                         'web_runnable': True,
                         'web_url': 'https://github.com/K2SOsint/Legendary_OSINT'},
                     {   'id': 'spiderfoot',
                         'input': 'домен, IP, почта или имя человека',
                         'install_guide': {   'docker': 'docker run -p 5001:5001 spiderfoot',
                                              'git': 'git clone https://github.com/smicallef/spiderfoot.git',
                                              'notes': 'Поднимает полноценную веб-лабораторию с интерактивным графом '
                                                       'связей.',
                                              'pip_or_pkg': 'pip3 install -r requirements.txt',
                                              'usage': 'python3 sf.py -l 127.0.0.1:5001 # Веб-панель'},
                         'launch': {   'href': 'https://github.com/smicallef/spiderfoot',
                                       'label': '📖 Открыть SpiderFoot на GitHub',
                                       'type': 'url'},
                         'name': '🕷️ Автоматический комбайн расследований (SpiderFoot)',
                         'purpose': '🤖 Робот для сбора разведданных: сам связывает между собой IP-адреса, домены, '
                                    'почты и телефоны одного человека или компании в единую карту.',
                         'repo': 'https://github.com/smicallef/spiderfoot',
                         'web_runnable': False,
                         'web_url': 'https://www.spiderfoot.net/'},
                     {   'id': 'maltego',
                         'input': 'имя, домен или организация',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': '# Профессиональная программа для ПК',
                                              'notes': 'Мировой стандарт визуального анализа связей в детективных '
                                                       'расследованиях.',
                                              'pip_or_pkg': '# Доступна бесплатная версия Maltego Community Edition',
                                              'usage': 'Скачать с https://www.maltego.com/ и запустить визуальные '
                                                       'трансформации'},
                         'launch': {   'href': 'https://www.maltego.com/',
                                       'label': '🌐 Открыть сайт Maltego',
                                       'type': 'url'},
                         'name': '🌐 Визуальный граф связей между людьми и сайтами (Maltego)',
                         'purpose': '🗺️ Рисует интерактивную схему связей: кто с кем общается, какими сайтами владеет '
                                    'и через какие компании связан.',
                         'repo': 'https://github.com/maltego',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://www.maltego.com/'},
                     {   'id': 'osint_framework',
                         'input': 'выбор категории на интерактивной карте',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': 'git clone https://github.com/lockfale/osint-framework.git',
                                              'notes': 'Самый структурированный путеводитель по поиску информации в '
                                                       'мире.',
                                              'pip_or_pkg': '# Доступно онлайн',
                                              'usage': 'Открыть сайт https://osintframework.com/ и выбрать нужный '
                                                       'раздел данных'},
                         'launch': {   'href': 'https://osintframework.com/',
                                       'label': '🌐 Открыть OSINT Framework',
                                       'type': 'url'},
                         'name': '🌳 Карта-путеводитель по всем OSINT инструментам мира',
                         'purpose': '🧭 Большое интерактивное дерево всех бесплатных сервисов интернета для поиска '
                                    'людей, транспорта, документов и геолокаций.',
                         'repo': 'https://github.com/lockfale/osint-framework',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://osintframework.com/'}]},
    {   'desc': 'Инструменты проверки номеров телефонов, оператора, региона и поиска регистраций по email-адресам.',
        'id': 'email_checks',
        'title': '📧 Почта и Телефонная разведка (Email & Phone)',
        'tools': [   {   'id': 'phoneinfoga_recon',
                         'input': 'номер телефона (например, +79991234567)',
                         'install_guide': {   'docker': '# Работает автономно в WebApp',
                                              'git': '# Встроенный в систему определитель номеров',
                                              'notes': 'Показывает оператора, город и открывает чат WhatsApp без '
                                                       'сохранения контакта.',
                                              'pip_or_pkg': 'pip install phonenumbers httpx',
                                              'usage': 'Введите номер телефона в международном формате (с +7 или '
                                                       '+380)'},
                         'launch': {'action': 'scan_phone', 'label': '⚡ Проверить телефон в WebApp', 'type': 'api'},
                         'name': '📱 Проверка номера телефона: оператор, город, чаты (PhoneInfoga)',
                         'purpose': '🔍 Узнает страну, оператора связи (МТС, Билайн, Мегафон и др.), регион номера и '
                                    'дает прямые ссылки на чат в WhatsApp и поиск в Telegram в один клик.',
                         'repo': 'https://github.com/sundowndev/phoneinfoga',
                         'scan_type': 'phone',
                         'web_runnable': True,
                         'web_url': 'https://github.com/sundowndev/phoneinfoga'},
                     {   'id': 'holehe',
                         'input': 'адрес почты (например, user@gmail.com)',
                         'install_guide': {   'docker': '# Работает автономно в WebApp',
                                              'git': '# Встроенный в систему веб-чекер почты',
                                              'notes': 'Проверяет наличие учетной записи без отправки писем жертве.',
                                              'pip_or_pkg': 'pip install holehe',
                                              'usage': 'Введите адрес электронной почты и нажмите «Сканировать»'},
                         'launch': {'action': 'scan_email', 'label': '⚡ Проверить регистрацию почты', 'type': 'api'},
                         'name': '📧 Проверка email: на каких сайтах есть аккаунт (Holehe)',
                         'purpose': '📬 Проверяет, зарегистрирована ли почта на 120+ популярных сервисах (Instagram, '
                                    'Twitter, Discord, Steam, Госуслуги и др.) абсолютно анонимно для владельца.',
                         'repo': 'https://github.com/megadose/holehe',
                         'scan_type': 'email',
                         'web_runnable': True,
                         'web_url': 'https://github.com/megadose/holehe'},
                     {   'id': 'epieos',
                         'input': 'email адрес',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': '# Облачный онлайн-сервис',
                                              'notes': 'Позволяет узнать имя владельца и его отметки на картах.',
                                              'pip_or_pkg': '# Доступно через Web UI',
                                              'usage': 'Открыть сайт https://epieos.com/ и ввести адрес почты'},
                         'launch': {   'href': 'https://epieos.com/',
                                       'label': '🌐 Открыть сервис Epieos Онлайн',
                                       'type': 'url'},
                         'name': '👤 Поиск информации о владельце email (Epieos)',
                         'purpose': '🔎 Находит привязанный профиль Google, имя владельца, аватарку и отзывы на картах '
                                    'по обычному адресу электронной почты.',
                         'repo': 'https://github.com/epieos',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://epieos.com/'}]},
    {   'desc': 'Универсальные сервисы для проверки IP-адресов, открытых портов, подключенных устройств и DNS-записей.',
        'id': 'security_utilities',
        'title': '🛠️ Полезные сетевые утилиты и Shodan',
        'tools': [   {   'id': 'cyberchef',
                         'input': 'закодированный текст или строка',
                         'install_guide': {   'docker': '# Не требуется',
                                              'git': 'git clone https://github.com/gchq/CyberChef.git',
                                              'notes': 'Работает прямо в браузере без отправки ваших данных на сервер.',
                                              'pip_or_pkg': '# Доступна онлайн-версия',
                                              'usage': 'Открыть сайт https://gchq.github.io/CyberChef/ в браузере'},
                         'launch': {   'href': 'https://gchq.github.io/CyberChef/',
                                       'label': '🌐 Открыть CyberChef Онлайн',
                                       'type': 'url'},
                         'name': '🧰 Кибер-кухня: расшифровка любого текста и кода (CyberChef)',
                         'purpose': '🔓 Универсальный онлайн-декодер: раскодирует непонятные наборы символов (Base64, '
                                    'Hex, URL-кодировку), распаковывает архивы и читает служебные данные.',
                         'repo': 'https://github.com/gchq/CyberChef',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://gchq.github.io/CyberChef/'},
                     {   'id': 'ipinfo',
                         'input': 'IP-адрес (например, 8.8.8.8)',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный в систему чекер IP',
                                              'notes': 'Мгновенно идентифицирует мобильных операторов, хостинги и VPN.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите IP-адрес для определения страны, города и провайдера'},
                         'launch': {'action': 'scan_ip', 'label': '⚡ Проверить IP в WebApp', 'type': 'api'},
                         'name': '📍 Определение провайдера и города по IP-адресу (IP-API)',
                         'purpose': '🌍 Показывает, в каком городе находится компьютер или сервер, какому '
                                    'интернет-провайдеру принадлежит и не используется ли VPN или датацентр.',
                         'repo': 'https://github.com/ipinfo',
                         'scan_type': 'ip',
                         'web_runnable': True,
                         'web_url': 'https://ipinfo.io/'},
                     {   'id': 'shodan_search',
                         'input': 'IP-адрес, домен или поисковый запрос',
                         'install_guide': {   'docker': '# Доступен через shodan.io',
                                              'git': 'git clone https://github.com/achillean/shodan-python.git',
                                              'notes': 'Позволяет узнать, какие порты и службы открыты на сервере.',
                                              'pip_or_pkg': 'pip install shodan',
                                              'usage': 'Открыть сайт https://www.shodan.io/ и ввести IP или поисковый '
                                                       'запрос'},
                         'launch': {'href': 'https://www.shodan.io/', 'label': '🌐 Открыть Shodan.io', 'type': 'url'},
                         'name': '🌐 Поисковик подключенных к сети камер и серверов (Shodan)',
                         'purpose': '🔭 Находит открытые веб-камеры, умные устройства, сервера и базы данных, '
                                    'оставленные без пароля в свободном доступе.',
                         'repo': 'https://github.com/achillean/shodan-python',
                         'scan_type': 'web_link',
                         'web_runnable': True,
                         'web_url': 'https://www.shodan.io/'},
                     {   'id': 'dns_recon',
                         'input': 'домен сайта (например, google.com)',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный DNS анализатор',
                                              'notes': 'Помогает выявить реальный сервер сайта за Cloudflare.',
                                              'pip_or_pkg': 'pip install dnspython httpx',
                                              'usage': 'Введите домен для проверки записей A, MX, NS и TXT'},
                         'launch': {'action': 'scan_domain', 'label': '⚡ Проверить DNS домена', 'type': 'api'},
                         'name': '📜 Проверка почтовых и серверных настроек домена (DNS Recon)',
                         'purpose': '✉️ Показывает, через какие сервера ходит почта сайта, защищен ли домен от '
                                    'подделки писем мошенниками (SPF, DKIM, DMARC) и где он размещен.',
                         'repo': 'https://github.com/lunar-recon/dns',
                         'scan_type': 'domain',
                         'web_runnable': True,
                         'web_url': 'https://dnschecker.org/'}]},
    {   'desc': 'Глубокая разведка по исходному коду, коммитам разработчиков, криптовалютным балансам и кошелькам.',
        'id': 'hacker_crypto_git',
        'title': '💻 GitHub, Блокчейн & Deep OSINT',
        'tools': [   {   'id': 'github_recon',
                         'input': 'юзернейм на GitHub (например, torvalds)',
                         'install_guide': {   'docker': '# Работает автономно в WebApp',
                                              'git': '# Встроенный в систему веб-сканер GitHub API',
                                              'notes': 'Находит настоящую почту программиста из истории Push-событий.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите юзернейм на GitHub для извлечения реального email '
                                                       'автора'},
                         'launch': {'action': 'scan_github', 'label': '⚡ Найти почту автора', 'type': 'api'},
                         'name': '💻 Поиск скрытой почты разработчика на GitHub',
                         'purpose': '🔍 Находит реальный адрес электронной почты и имя автора проекта, спрятанные в '
                                    'истории загрузок кода (git-коммитах), даже если они скрыты в профиле.',
                         'repo': 'https://github.com/techgaun/github-dorks',
                         'scan_type': 'github',
                         'web_runnable': True,
                         'web_url': 'https://github.com/'},
                     {   'id': 'crypto_tracker',
                         'input': 'адрес криптокошелька',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный блокчейн-сканер',
                                              'notes': 'Позволяет быстро отследить движение средств и историю '
                                                       'транзакций.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите адрес кошелька BTC, ETH или TRON (USDT TRC-20)'},
                         'launch': {'action': 'scan_crypto', 'label': '⚡ Посмотреть баланс и переводы', 'type': 'api'},
                         'name': '💰 Проверка баланса и переводов криптокошелька',
                         'purpose': '🪙 Показывает реальный баланс кошелька, дату первой и последней транзакции, общую '
                                    'сумму всех входящих денег в сетях Bitcoin, Ethereum, USDT и Solana.',
                         'repo': 'https://github.com/blockchair',
                         'scan_type': 'crypto',
                         'web_runnable': True,
                         'web_url': 'https://blockchair.com/'},
                     {   'id': 'holehe_osint',
                         'input': 'email адрес',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный мульти-сервисный чекер',
                                              'notes': 'Помогает узнать все сайты, где зарегистрирован интересующий '
                                                       'человек.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите почту для составления цифрового профиля'},
                         'launch': {'action': 'scan_email', 'label': '⚡ Проверить почту', 'type': 'api'},
                         'name': '🌐 Полный цифровой профиль по адресу почты (Holehe Hub)',
                         'purpose': '📧 Составляет список всех социальных сетей, онлайн-магазинов и форумов, где '
                                    'человек когда-либо создавал учетную запись с этой почтой.',
                         'repo': 'https://github.com/megadose/holehe',
                         'scan_type': 'email',
                         'web_runnable': True,
                         'web_url': 'https://github.com/megadose/holehe'}]},
    {   'desc': 'Сквозной сбор связей человека, просмотр удаленных веб-страниц и скрытых поддоменов через '
                'SSL-сертификаты.',
        'id': 'deep_archive_recon',
        'title': '🏛️ Архивы, Удаленные данные & Сквозной Auto-Recon',
        'tools': [   {   'id': 'autorecon',
                         'input': 'никнейм, почта, телефон или ссылка',
                         'install_guide': {   'docker': '# Встроенный сервис',
                                              'git': '# Центральный аналитический движок платформы',
                                              'notes': 'Объединяет аккаунты, почты, коммиты и строит интерактивную '
                                                       'карту связей.',
                                              'pip_or_pkg': 'pip install httpx beautifulsoup4',
                                              'usage': 'Введите любую цель для запуска автоматического сквозного '
                                                       'сбора'},
                         'launch': {   'action': 'scan_autorecon',
                                       'label': '⚡ Запустить полное расследование',
                                       'type': 'api'},
                         'name': '⚡ Сквозное автоматическое расследование и граф связей',
                         'purpose': '🕸️ Проводит комплексный поиск сразу по всем базам (ник, почта, телефон, соцсети), '
                                    'связывает все найденные данные воедино и рисует наглядный граф связей.',
                         'repo': 'https://github.com/sherlock-project/sherlock',
                         'scan_type': 'autorecon',
                         'web_runnable': True,
                         'web_url': ''},
                     {   'id': 'wayback_recon',
                         'input': 'ссылка на сайт или профиль',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный сканер Web Archive API',
                                              'notes': 'Позволяет увидеть текст страницы до ее редактирования или '
                                                       'удаления.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите ссылку на страницу для поиска сохраненных снимков'},
                         'launch': {'action': 'scan_wayback', 'label': '⚡ Найти сохраненные снимки', 'type': 'api'},
                         'name': '🏛️ Поиск удаленных версий страниц в Веб-Архиве',
                         'purpose': '⏳ Находит старые копии сайтов и профилей в соцсетях до того, как с них стерли '
                                    'компрометирующую информацию или контакты.',
                         'repo': 'https://github.com/internetarchive/wayback',
                         'scan_type': 'wayback',
                         'web_runnable': True,
                         'web_url': 'https://web.archive.org/'},
                     {   'id': 'crtsh',
                         'input': 'домен компании (например, bank.com)',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Сканер глобального реестра сертификатов',
                                              'notes': 'Находит поддомены, которых нет в открытых записях DNS.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите домен для поиска всех зарегистрированных поддоменов'},
                         'launch': {'action': 'scan_crtsh', 'label': '⚡ Проверить сертификаты', 'type': 'api'},
                         'name': '📜 Поиск скрытых поддоменов через SSL-сертификаты (crt.sh)',
                         'purpose': '🔍 Находит секретные тестовые страницы и закрытые поддомены компании, на которые '
                                    'когда-либо выпускались официальные сертификаты безопасности.',
                         'repo': 'https://github.com/crtsh',
                         'scan_type': 'crtsh',
                         'web_runnable': True,
                         'web_url': 'https://crt.sh/'}]},
    {   'desc': 'Мастер боевых поисковых дорков, автоопределение типов паролей, расшифровка JWT токенов и Base64/Hex.',
        'id': 'cyber_tools_lab',
        'title': '🧰 Лаборатория Декодеров, Дорки & Крипто-форензика',
        'tools': [   {   'id': 'cyberchef_decoder',
                         'input': 'зашифрованная строка или текст',
                         'install_guide': {   'docker': '# Работает прямо в браузере',
                                              'git': '# Встроенный в систему декодер',
                                              'notes': 'Позволяет быстро разобрать непонятный шифр без лишних '
                                                       'программ.',
                                              'pip_or_pkg': '# Не требуется',
                                              'usage': 'Вставьте закодированную строку и выберите нужный тип '
                                                       'расшифровки'},
                         'launch': {'action': 'open_decoder', 'label': '⚡ Открыть декодер', 'type': 'api'},
                         'name': '🔓 Быстрый декодер текста (Base64, Hex, URL, ROT13)',
                         'purpose': '🔤 Мгновенно превращает непонятный закодированный текст или шифр в обычные '
                                    'читаемые русские или английские слова.',
                         'repo': 'https://github.com/gchq/CyberChef',
                         'scan_type': 'decoder',
                         'web_runnable': True,
                         'web_url': ''},
                     {   'id': 'hash_identifier',
                         'input': 'строка хеша (например, 5d41402abc4b2a76b9719d911017c592)',
                         'install_guide': {   'docker': '# Работает в WebApp',
                                              'git': '# Встроенный идентификатор хешей',
                                              'notes': 'Показывает тип шифрования и разрядность.',
                                              'pip_or_pkg': '# Не требуется',
                                              'usage': 'Вставьте строку хеша для определения алгоритма'},
                         'launch': {'action': 'open_decoder', 'label': '⚡ Распознать тип хеша', 'type': 'api'},
                         'name': '🔐 Определение типа пароля или хеша (Hash Identifier)',
                         'purpose': '🎯 Определяет, каким алгоритмом был зашифрован пароль или файл (MD5, SHA-256, '
                                    'bcrypt, NTLM) и можно ли его расшифровать.',
                         'repo': 'https://github.com/psypanda/hashID',
                         'scan_type': 'decoder',
                         'web_runnable': True,
                         'web_url': ''},
                     {   'id': 'jwt_decoder',
                         'input': 'JWT токен (например, eyJhbGciOi...)',
                         'install_guide': {   'docker': '# Работает в браузере',
                                              'git': '# Встроенный JWT парсер',
                                              'notes': 'Показывает срок действия токена и скрытые данные пользователя.',
                                              'pip_or_pkg': '# Не требуется',
                                              'usage': 'Вставьте токен для разбора структуры и прав'},
                         'launch': {'action': 'open_decoder', 'label': '⚡ Разобрать JWT токен', 'type': 'api'},
                         'name': '🛡️ Просмотр данных в токенах авторизации (JWT Decoder)',
                         'purpose': '🔑 Показывает, какая информация (ID пользователя, права, срок действия) зашита '
                                    'внутри веб-токена авторизации без знания секретного ключа.',
                         'repo': 'https://github.com/jwtk/jjwt',
                         'scan_type': 'decoder',
                         'web_runnable': True,
                         'web_url': 'https://jwt.io/'},
                     {   'id': 'crypto_forensics',
                         'input': 'адрес Bitcoin, Ethereum или TRON кошелька',
                         'install_guide': {   'docker': '# Работает автономно',
                                              'git': '# Встроенный блокчейн-анализатор',
                                              'notes': 'Автоматически определяет сеть (BTC, ETH, TRX) и баланс.',
                                              'pip_or_pkg': 'pip install httpx',
                                              'usage': 'Введите адрес кошелька для получения сводки движения активов'},
                         'launch': {'action': 'scan_crypto', 'label': '⚡ Анализ транзакций', 'type': 'api'},
                         'name': '🪙 Форензика криптокошельков (BTC, ETH, TRON/USDT)',
                         'purpose': '💰 Проверяет историю баланса кошелька, активность за все время и строит удобную '
                                    'финансовую сводку для расследований.',
                         'repo': 'https://github.com/blockchair',
                         'scan_type': 'crypto',
                         'web_runnable': True,
                         'web_url': 'https://blockchair.com/'},
                     {   'id': 'dorking_wizard',
                         'input': 'никнейм человека, ключевое слово или сайт',
                         'install_guide': {   'docker': '# Работает в WebApp',
                                              'git': '# Встроенный генератор поисковых матриц',
                                              'notes': 'Позволяет запустить точечный поиск по базам данных в один '
                                                       'клик.',
                                              'pip_or_pkg': '# Не требуется',
                                              'usage': 'Введите цель для генерации 25+ боевых дорков с прямыми '
                                                       'ссылками'},
                         'launch': {'action': 'scan_dorks', 'label': '⚡ Сгенерировать поисковые ссылки', 'type': 'api'},
                         'name': '🧙\u200d♂️ Мастер поисковых запросов Google и Yandex (Dork Builder)',
                         'purpose': '🎯 Создает специальные готовые запросы для Google и Яндекс, которые в 1 клик '
                                    'находят скрытые документы (.pdf, .xlsx), утекшие пароли и закрытые страницы '
                                    'человека.',
                         'repo': 'https://github.com/techgaun/github-dorks',
                         'scan_type': 'dorks',
                         'web_runnable': True,
                         'web_url': 'https://google.com/'}]}]

def get_all_tools():
    """Возвращает плоский список всех инструментов."""
    tools = []
    for category in CATALOG:
        for tool in category.get("tools", []):
            t = dict(tool)
            t["category_id"] = category["id"]
            t["category_title"] = category["title"]
            tools.append(t)
    return tools


def get_tool_by_id(tool_id: str):
    """Поиск инструмента по ID."""
    for category in CATALOG:
        for tool in category.get("tools", []):
            if tool["id"] == tool_id:
                t = dict(tool)
                t["category_id"] = category["id"]
                t["category_title"] = category["title"]
                return t
    return None


def get_tools_by_category(category_id: str):
    """Возвращает список инструментов для категории."""
    for category in CATALOG:
        if category["id"] == category_id:
            return category.get("tools", [])
    return []


def search_tools(query: str):
    """Поиск по названию, описанию, тегам и ID."""
    q = query.lower().strip()
    results = []
    for tool in get_all_tools():
        if (
            q in tool["name"].lower()
            or q in tool["purpose"].lower()
            or q in tool["id"].lower()
            or q in tool.get("input", "").lower()
        ):
            results.append(tool)
    return results


def find_tool(tool_id: str):
    """Поиск инструмента по ID (алиас для find_tool)."""
    return get_tool_by_id(tool_id)


def normalize_catalog():
    """Возвращает нормализованный каталог."""
    return CATALOG


